### ISSUE TITLE
executing eslint brings error

### ISSUE THREAD

**Issue by PascalBru** [schl3ck/ios-scriptable-types#6]
I download the example directory and tried running the command `npx eslint .` but there I'm getting the following error:
_/scriptable/Welcome to Scriptable.js
57:18  error  Parsing error: Unexpected token req_

Is it not possible to use your files for eslint directly?

**Comment by schl3ck** [comment]
It is possible to use the files. The only problem is that ESLint doesn't support top-level await, which is currently a stage 3 proposal (https://github.com/tc39/proposal-top-level-await) but ESLint only supports stage 4 proposals.

There are two workarounds as far as I know:
1. Define the `await` keyword as a readonly global and wrap everything after it in parentheses. Now ESLint thinks that it is a function call and formats it that way (if enabled).
2. Use the parser `babel-eslint`. Please search the internet on how to use it.

**Comment by PascalBru** [comment]
THX for your help
